controller_frequency: 2.0

TrajectoryPlannerROS:

  holonomic_robot: false
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: false
  sim_time: 3.0
  meter_scoring: true
  pdist_scale: 0.9            
  gdist_scale: 1.0              
  publish_cost_grid_pc: false   
  oscillation_reset_dist: 0.1  
  escape_vel: -0.1
  heading_scoring_timestep: 0.8 
